name: hexo deployer

on:
  push:
    branches: 
      - hexo-g

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: setup hexo env
        run: |
          npm install hexo-cli -g
          npm install

      - name: generate public file
        run: |
          hexo clean
          hexo g
          ls
      
      - name: deploy
        env:
          GH_REF: github.com/rebortyang/rebortyang.github.io.git
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh


